package tenderplus

import (
	"encoding/json"
	"errors"
	"net/http"
	"strings"
	"time"

	"github.com/dauren/tender/internal/authctx"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

const (
	maxSavedLotHistoryEntries = 200
	maxSavedLotHistoryBytes   = 4 << 20
)

type participateLotInput struct {
	ID         uint       `json:"id"`
	Status     *string    `json:"status"`
	Comment    *string    `json:"comment"`
	AssignedTo *string    `json:"assigned_to"`
	Priority   *string    `json:"priority"`
	RiskLevel  *string    `json:"risk_level"`
	NextStep   *string    `json:"next_step"`
	Deadline   *time.Time `json:"deadline"`
	// Immutable lot metadata, reviewer/author, action_history and timestamps are
	// intentionally absent. They are loaded or generated by the server.
}

type parserLotSnapshot struct {
	ID            uint       `gorm:"column:id"`
	ExternalID    string     `gorm:"column:external_id"`
	Source        string     `gorm:"column:source"`
	Title         string     `gorm:"column:title"`
	Description   string     `gorm:"column:description"`
	Amount        *float64   `gorm:"column:amount"`
	StartDate     *time.Time `gorm:"column:start_date"`
	EndDate       *time.Time `gorm:"column:end_date"`
	PurchaseType  *string    `gorm:"column:purchase_type"`
	OrganizerName *string    `gorm:"column:organizer_name"`
	URL           string     `gorm:"column:url"`
}

func (parserLotSnapshot) TableName() string { return "parser_lots" }

type savedLotHistoryEntry struct {
	Status      string    `json:"status"`
	Comment     string    `json:"comment,omitempty"`
	AssignedTo  string    `json:"assignedTo,omitempty"`
	Reviewer    string    `json:"reviewer"`
	ActorUserID uint      `json:"actorUserId"`
	At          time.Time `json:"at"`
}

// ParticipateLotHandler changes workflow state without trusting audit or lot
// metadata supplied by the browser.
func ParticipateLotHandler(db *gorm.DB) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		identity, err := workspaceIdentity(r)
		if err != nil {
			writeWorkspaceRequestError(w, err, "Доступ запрещен")
			return
		}

		var input participateLotInput
		if err := decodeWorkspaceJSON(w, r, &input); err != nil {
			writeWorkspaceError(w, http.StatusBadRequest, "Неверный формат данных")
			return
		}
		if input.ID == 0 {
			writeWorkspaceError(w, http.StatusBadRequest, "ID не указан")
			return
		}

		var saved SavedLot
		err = db.WithContext(r.Context()).Transaction(func(tx *gorm.DB) error {
			var existing SavedLot
			lookupErr := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&existing, input.ID).Error
			if lookupErr != nil && !errors.Is(lookupErr, gorm.ErrRecordNotFound) {
				return lookupErr
			}

			if errors.Is(lookupErr, gorm.ErrRecordNotFound) {
				var source parserLotSnapshot
				if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&source, input.ID).Error; err != nil {
					if errors.Is(err, gorm.ErrRecordNotFound) {
						return newWorkspaceRequestError(http.StatusNotFound, "Тендер не найден")
					}
					return err
				}

				// Re-read after taking the parser row lock. This serializes two first
				// saves of the same parser lot and prevents a lost history entry.
				lookupErr = tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&existing, input.ID).Error
				if lookupErr != nil && !errors.Is(lookupErr, gorm.ErrRecordNotFound) {
					return lookupErr
				}
				if errors.Is(lookupErr, gorm.ErrRecordNotFound) {
					created, err := buildSavedLot(source, input, identity, time.Now().UTC())
					if err != nil {
						return err
					}
					saved = created
					if err := tx.Create(&saved).Error; err != nil {
						return err
					}
					return createStatusActivity(tx, saved, identity, saved.UpdatedAt)
				}
			}

			if err := authorizeSavedLotMutation(existing, identity); err != nil {
				return err
			}
			updated, err := updateSavedLot(existing, input, identity, time.Now().UTC())
			if err != nil {
				return err
			}
			saved = updated
			if err := tx.Save(&saved).Error; err != nil {
				return err
			}
			return createStatusActivity(tx, saved, identity, saved.UpdatedAt)
		})
		if err != nil {
			writeWorkspaceRequestError(w, err, "Ошибка сохранения лота")
			return
		}

		writeWorkspaceJSON(w, http.StatusOK, saved)
	}
}

func buildSavedLot(source parserLotSnapshot, input participateLotInput, identity authctx.Identity, now time.Time) (SavedLot, error) {
	status, err := requestedSavedLotStatus(input.Status, "participating")
	if err != nil {
		return SavedLot{}, err
	}
	priority, err := requestedPriority(input.Priority, "normal")
	if err != nil {
		return SavedLot{}, err
	}
	riskLevel, err := requestedRiskLevel(input.RiskLevel, "medium")
	if err != nil {
		return SavedLot{}, err
	}
	assignedTo := ""
	if identity.Role == "tender_specialist" {
		switch status {
		case "assignment_requested", "rejected":
			assignedTo = ""
		default:
			// A specialist can only assign a newly-created workflow item to
			// themselves. The browser-provided label is never trusted.
			assignedTo = identity.Name
		}
	} else {
		assignedTo, err = requestedAssignee(identity, SavedLot{}, input.AssignedTo)
		if err != nil {
			return SavedLot{}, err
		}
	}

	amount := float64(0)
	if source.Amount != nil {
		amount = *source.Amount
	}
	startDate := time.Time{}
	if source.StartDate != nil {
		startDate = source.StartDate.UTC()
	}
	endDate := time.Time{}
	if source.EndDate != nil {
		endDate = source.EndDate.UTC()
	}
	deadline := endDate
	if input.Deadline != nil {
		deadline = input.Deadline.UTC()
	}
	comment := stringValue(input.Comment)
	nextStep := stringValue(input.NextStep)
	if err := validateSavedLotText(comment, nextStep, assignedTo); err != nil {
		return SavedLot{}, err
	}

	saved := SavedLot{
		ID:              source.ID,
		ExternalID:      strings.TrimSpace(source.ExternalID),
		Source:          strings.TrimSpace(source.Source),
		Title:           firstNonEmpty(strings.TrimSpace(source.Title), "Без названия"),
		Description:     source.Description,
		Amount:          amount,
		Status:          status,
		Comment:         comment,
		AssignedTo:      assignedTo,
		Reviewer:        identity.Name,
		Priority:        priority,
		RiskLevel:       riskLevel,
		NextStep:        nextStep,
		Deadline:        deadline,
		StartDate:       startDate,
		EndDate:         endDate,
		PurchaseType:    pointerString(source.PurchaseType),
		OrganizerName:   pointerString(source.OrganizerName),
		PartnerLink:     strings.TrimSpace(source.URL),
		CreatedByUserID: identity.UserID,
		UpdatedByUserID: identity.UserID,
		CreatedAt:       now,
		UpdatedAt:       now,
	}
	if err := appendSavedLotHistory(&saved, identity, now); err != nil {
		return SavedLot{}, err
	}
	return saved, nil
}

func updateSavedLot(existing SavedLot, input participateLotInput, identity authctx.Identity, now time.Time) (SavedLot, error) {
	if input.Status != nil {
		status, err := requestedSavedLotStatus(input.Status, existing.Status)
		if err != nil {
			return SavedLot{}, err
		}
		existing.Status = status
	}
	if input.Comment != nil {
		existing.Comment = strings.TrimSpace(*input.Comment)
	}
	if input.AssignedTo != nil {
		assignedTo, err := requestedAssignee(identity, existing, input.AssignedTo)
		if err != nil {
			return SavedLot{}, err
		}
		existing.AssignedTo = assignedTo
	}
	if input.Priority != nil {
		priority, err := requestedPriority(input.Priority, existing.Priority)
		if err != nil {
			return SavedLot{}, err
		}
		existing.Priority = priority
	}
	if input.RiskLevel != nil {
		riskLevel, err := requestedRiskLevel(input.RiskLevel, existing.RiskLevel)
		if err != nil {
			return SavedLot{}, err
		}
		existing.RiskLevel = riskLevel
	}
	if input.NextStep != nil {
		existing.NextStep = strings.TrimSpace(*input.NextStep)
	}
	if input.Deadline != nil {
		existing.Deadline = input.Deadline.UTC()
	}
	if err := validateSavedLotText(existing.Comment, existing.NextStep, existing.AssignedTo); err != nil {
		return SavedLot{}, err
	}

	// Reviewer and audit timestamps always describe the authenticated actor.
	existing.Reviewer = identity.Name
	existing.UpdatedByUserID = identity.UserID
	existing.UpdatedAt = now
	if existing.CreatedByUserID == 0 && sameWorkspaceName(existing.AssignedTo, identity.Name) {
		existing.CreatedByUserID = identity.UserID
	}
	if err := appendSavedLotHistory(&existing, identity, now); err != nil {
		return SavedLot{}, err
	}
	return existing, nil
}

func appendSavedLotHistory(lot *SavedLot, identity authctx.Identity, now time.Time) error {
	entries := make([]json.RawMessage, 0, 8)
	if raw := strings.TrimSpace(lot.ActionHistory); raw != "" && len(raw) <= maxSavedLotHistoryBytes {
		if err := json.Unmarshal([]byte(raw), &entries); err != nil {
			// Historical data created by older clients may be malformed. Do not
			// allow it to prevent a server-authenticated audit entry.
			entries = entries[:0]
		}
	}
	entry, err := json.Marshal(savedLotHistoryEntry{
		Status:      lot.Status,
		Comment:     auditTextSummary(lot.Comment, 2_000),
		AssignedTo:  lot.AssignedTo,
		Reviewer:    identity.Name,
		ActorUserID: identity.UserID,
		At:          now,
	})
	if err != nil {
		return err
	}
	entries = append(entries, entry)
	if len(entries) > maxSavedLotHistoryEntries {
		entries = entries[len(entries)-maxSavedLotHistoryEntries:]
	}
	history, err := json.Marshal(entries)
	if err != nil {
		return err
	}
	lot.ActionHistory = string(history)
	return nil
}

func auditTextSummary(value string, maxRunes int) string {
	value = strings.TrimSpace(value)
	runes := []rune(value)
	if maxRunes > 0 && len(runes) > maxRunes {
		return string(runes[:maxRunes])
	}
	return value
}

func createStatusActivity(tx *gorm.DB, lot SavedLot, identity authctx.Identity, now time.Time) error {
	return tx.Create(&TenderActivity{
		SavedLotID:  lot.ID,
		Action:      "status_changed",
		Status:      lot.Status,
		Actor:       identity.Name,
		ActorUserID: identity.UserID,
		Message:     lot.Comment,
		CreatedAt:   now,
	}).Error
}

func requestedSavedLotStatus(value *string, fallback string) (string, error) {
	status := strings.TrimSpace(fallback)
	if value != nil {
		status = strings.TrimSpace(*value)
	}
	if !isSavedLotStatus(status) {
		return "", newWorkspaceRequestError(http.StatusBadRequest, "Некорректный статус лота")
	}
	return status, nil
}

func isSavedLotStatus(status string) bool {
	switch strings.TrimSpace(status) {
	case "active", "review", "assignment_requested", "in_work", "participating", "submitted", "waiting_result", "won", "lost", "rejected", "archived":
		return true
	default:
		return false
	}
}

func requestedPriority(value *string, fallback string) (string, error) {
	priority := strings.TrimSpace(fallback)
	if value != nil && strings.TrimSpace(*value) != "" {
		priority = strings.TrimSpace(*value)
	}
	switch priority {
	case "low", "normal", "high", "urgent":
		return priority, nil
	default:
		return "", newWorkspaceRequestError(http.StatusBadRequest, "Некорректный приоритет")
	}
}

func requestedRiskLevel(value *string, fallback string) (string, error) {
	risk := strings.TrimSpace(fallback)
	if value != nil && strings.TrimSpace(*value) != "" {
		risk = strings.TrimSpace(*value)
	}
	switch risk {
	case "low", "medium", "high":
		return risk, nil
	default:
		return "", newWorkspaceRequestError(http.StatusBadRequest, "Некорректный уровень риска")
	}
}

func validateSavedLotText(comment, nextStep, assignedTo string) error {
	if len([]rune(comment)) > 10_000 || len([]rune(nextStep)) > 10_000 {
		return newWorkspaceRequestError(http.StatusBadRequest, "Текстовое поле слишком длинное")
	}
	if len([]rune(assignedTo)) > 255 {
		return newWorkspaceRequestError(http.StatusBadRequest, "Имя ответственного слишком длинное")
	}
	return nil
}

func stringValue(value *string) string {
	if value == nil {
		return ""
	}
	return strings.TrimSpace(*value)
}

func pointerString(value *string) string {
	if value == nil {
		return ""
	}
	return strings.TrimSpace(*value)
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			return trimmed
		}
	}
	return ""
}

// GetSavedLotsHandler returns the shared workflow list. Field mutations are
// still authorized per-lot in the write handlers.
func GetSavedLotsHandler(db *gorm.DB) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var lots []SavedLot
		q := db.WithContext(r.Context()).Order("created_at desc")
		if status := strings.TrimSpace(r.URL.Query().Get("status")); status != "" {
			if !isSavedLotStatus(status) {
				writeWorkspaceError(w, http.StatusBadRequest, "Некорректный статус лота")
				return
			}
			q = q.Where("status = ?", status)
		}
		if err := q.Find(&lots).Error; err != nil {
			writeWorkspaceError(w, http.StatusInternalServerError, "Ошибка получения лотов")
			return
		}
		writeWorkspaceJSON(w, http.StatusOK, lots)
	}
}

// DeleteSavedLotHandler deletes the workflow row and atomically preserves a
// separate activity record identifying the actor.
func DeleteSavedLotHandler(db *gorm.DB) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		identity, err := workspaceIdentity(r)
		if err != nil {
			writeWorkspaceRequestError(w, err, "Доступ запрещен")
			return
		}
		lotID, ok := lotIDFromRequest(w, r)
		if !ok {
			return
		}

		err = db.WithContext(r.Context()).Transaction(func(tx *gorm.DB) error {
			var lot SavedLot
			if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&lot, lotID).Error; err != nil {
				if errors.Is(err, gorm.ErrRecordNotFound) {
					return newWorkspaceRequestError(http.StatusNotFound, "Лот не найден")
				}
				return err
			}
			if err := authorizeSavedLotMutation(lot, identity); err != nil {
				return err
			}
			now := time.Now().UTC()
			if err := tx.Create(&TenderActivity{
				SavedLotID:  lot.ID,
				Action:      "lot_deleted",
				Status:      lot.Status,
				Actor:       identity.Name,
				ActorUserID: identity.UserID,
				CreatedAt:   now,
			}).Error; err != nil {
				return err
			}
			return tx.Delete(&lot).Error
		})
		if err != nil {
			writeWorkspaceRequestError(w, err, "Ошибка удаления лота")
			return
		}
		writeWorkspaceJSON(w, http.StatusOK, map[string]bool{"success": true})
	}
}
