/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminTendersRouteImport } from './routes/_admin/tenders'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminNotificationsRouteImport } from './routes/_admin/notifications'
import { Route as AdminDictionariesRouteImport } from './routes/_admin/dictionaries'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminCompaniesRouteImport } from './routes/_admin/companies'
import { Route as AdminBidsRouteImport } from './routes/_admin/bids'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin/analytics'
import { Route as AdminTendersIndexRouteImport } from './routes/_admin/tenders.index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/_admin/analytics.index'
import { Route as AdminTendersTenderIdRouteImport } from './routes/_admin/tenders.$tenderId'
import { Route as AdminAnalyticsWinnersRouteImport } from './routes/_admin/analytics.winners'
import { Route as AdminAnalyticsPricesRouteImport } from './routes/_admin/analytics.prices'
import { Route as AdminAnalyticsHistoricalRouteImport } from './routes/_admin/analytics.historical'
import { Route as AdminAnalyticsCustomersRouteImport } from './routes/_admin/analytics.customers'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTendersRoute = AdminTendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDictionariesRoute = AdminDictionariesRouteImport.update({
  id: '/dictionaries',
  path: '/dictionaries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBidsRoute = AdminBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTendersIndexRoute = AdminTendersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTendersRoute,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminTendersTenderIdRoute = AdminTendersTenderIdRouteImport.update({
  id: '/$tenderId',
  path: '/$tenderId',
  getParentRoute: () => AdminTendersRoute,
} as any)
const AdminAnalyticsWinnersRoute = AdminAnalyticsWinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsPricesRoute = AdminAnalyticsPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsHistoricalRoute =
  AdminAnalyticsHistoricalRouteImport.update({
    id: '/historical',
    path: '/historical',
    getParentRoute: () => AdminAnalyticsRoute,
  } as any)
const AdminAnalyticsCustomersRoute = AdminAnalyticsCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AdminAnalyticsRouteWithChildren
  '/bids': typeof AdminBidsRoute
  '/companies': typeof AdminCompaniesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/dictionaries': typeof AdminDictionariesRoute
  '/notifications': typeof AdminNotificationsRoute
  '/settings': typeof AdminSettingsRoute
  '/tenders': typeof AdminTendersRouteWithChildren
  '/users': typeof AdminUsersRoute
  '/analytics/customers': typeof AdminAnalyticsCustomersRoute
  '/analytics/historical': typeof AdminAnalyticsHistoricalRoute
  '/analytics/prices': typeof AdminAnalyticsPricesRoute
  '/analytics/winners': typeof AdminAnalyticsWinnersRoute
  '/tenders/$tenderId': typeof AdminTendersTenderIdRoute
  '/analytics/': typeof AdminAnalyticsIndexRoute
  '/tenders/': typeof AdminTendersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bids': typeof AdminBidsRoute
  '/companies': typeof AdminCompaniesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/dictionaries': typeof AdminDictionariesRoute
  '/notifications': typeof AdminNotificationsRoute
  '/settings': typeof AdminSettingsRoute
  '/users': typeof AdminUsersRoute
  '/analytics/customers': typeof AdminAnalyticsCustomersRoute
  '/analytics/historical': typeof AdminAnalyticsHistoricalRoute
  '/analytics/prices': typeof AdminAnalyticsPricesRoute
  '/analytics/winners': typeof AdminAnalyticsWinnersRoute
  '/tenders/$tenderId': typeof AdminTendersTenderIdRoute
  '/analytics': typeof AdminAnalyticsIndexRoute
  '/tenders': typeof AdminTendersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/analytics': typeof AdminAnalyticsRouteWithChildren
  '/_admin/bids': typeof AdminBidsRoute
  '/_admin/companies': typeof AdminCompaniesRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/dictionaries': typeof AdminDictionariesRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/tenders': typeof AdminTendersRouteWithChildren
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/analytics/customers': typeof AdminAnalyticsCustomersRoute
  '/_admin/analytics/historical': typeof AdminAnalyticsHistoricalRoute
  '/_admin/analytics/prices': typeof AdminAnalyticsPricesRoute
  '/_admin/analytics/winners': typeof AdminAnalyticsWinnersRoute
  '/_admin/tenders/$tenderId': typeof AdminTendersTenderIdRoute
  '/_admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/_admin/tenders/': typeof AdminTendersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/bids'
    | '/companies'
    | '/dashboard'
    | '/dictionaries'
    | '/notifications'
    | '/settings'
    | '/tenders'
    | '/users'
    | '/analytics/customers'
    | '/analytics/historical'
    | '/analytics/prices'
    | '/analytics/winners'
    | '/tenders/$tenderId'
    | '/analytics/'
    | '/tenders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bids'
    | '/companies'
    | '/dashboard'
    | '/dictionaries'
    | '/notifications'
    | '/settings'
    | '/users'
    | '/analytics/customers'
    | '/analytics/historical'
    | '/analytics/prices'
    | '/analytics/winners'
    | '/tenders/$tenderId'
    | '/analytics'
    | '/tenders'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/analytics'
    | '/_admin/bids'
    | '/_admin/companies'
    | '/_admin/dashboard'
    | '/_admin/dictionaries'
    | '/_admin/notifications'
    | '/_admin/settings'
    | '/_admin/tenders'
    | '/_admin/users'
    | '/_admin/analytics/customers'
    | '/_admin/analytics/historical'
    | '/_admin/analytics/prices'
    | '/_admin/analytics/winners'
    | '/_admin/tenders/$tenderId'
    | '/_admin/analytics/'
    | '/_admin/tenders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tenders': {
      id: '/_admin/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof AdminTendersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notifications': {
      id: '/_admin/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dictionaries': {
      id: '/_admin/dictionaries'
      path: '/dictionaries'
      fullPath: '/dictionaries'
      preLoaderRoute: typeof AdminDictionariesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/companies': {
      id: '/_admin/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/bids': {
      id: '/_admin/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof AdminBidsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tenders/': {
      id: '/_admin/tenders/'
      path: '/'
      fullPath: '/tenders/'
      preLoaderRoute: typeof AdminTendersIndexRouteImport
      parentRoute: typeof AdminTendersRoute
    }
    '/_admin/analytics/': {
      id: '/_admin/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/_admin/tenders/$tenderId': {
      id: '/_admin/tenders/$tenderId'
      path: '/$tenderId'
      fullPath: '/tenders/$tenderId'
      preLoaderRoute: typeof AdminTendersTenderIdRouteImport
      parentRoute: typeof AdminTendersRoute
    }
    '/_admin/analytics/winners': {
      id: '/_admin/analytics/winners'
      path: '/winners'
      fullPath: '/analytics/winners'
      preLoaderRoute: typeof AdminAnalyticsWinnersRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/_admin/analytics/prices': {
      id: '/_admin/analytics/prices'
      path: '/prices'
      fullPath: '/analytics/prices'
      preLoaderRoute: typeof AdminAnalyticsPricesRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/_admin/analytics/historical': {
      id: '/_admin/analytics/historical'
      path: '/historical'
      fullPath: '/analytics/historical'
      preLoaderRoute: typeof AdminAnalyticsHistoricalRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/_admin/analytics/customers': {
      id: '/_admin/analytics/customers'
      path: '/customers'
      fullPath: '/analytics/customers'
      preLoaderRoute: typeof AdminAnalyticsCustomersRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
  }
}

interface AdminAnalyticsRouteChildren {
  AdminAnalyticsCustomersRoute: typeof AdminAnalyticsCustomersRoute
  AdminAnalyticsHistoricalRoute: typeof AdminAnalyticsHistoricalRoute
  AdminAnalyticsPricesRoute: typeof AdminAnalyticsPricesRoute
  AdminAnalyticsWinnersRoute: typeof AdminAnalyticsWinnersRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
}

const AdminAnalyticsRouteChildren: AdminAnalyticsRouteChildren = {
  AdminAnalyticsCustomersRoute: AdminAnalyticsCustomersRoute,
  AdminAnalyticsHistoricalRoute: AdminAnalyticsHistoricalRoute,
  AdminAnalyticsPricesRoute: AdminAnalyticsPricesRoute,
  AdminAnalyticsWinnersRoute: AdminAnalyticsWinnersRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
}

const AdminAnalyticsRouteWithChildren = AdminAnalyticsRoute._addFileChildren(
  AdminAnalyticsRouteChildren,
)

interface AdminTendersRouteChildren {
  AdminTendersTenderIdRoute: typeof AdminTendersTenderIdRoute
  AdminTendersIndexRoute: typeof AdminTendersIndexRoute
}

const AdminTendersRouteChildren: AdminTendersRouteChildren = {
  AdminTendersTenderIdRoute: AdminTendersTenderIdRoute,
  AdminTendersIndexRoute: AdminTendersIndexRoute,
}

const AdminTendersRouteWithChildren = AdminTendersRoute._addFileChildren(
  AdminTendersRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRouteWithChildren
  AdminBidsRoute: typeof AdminBidsRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDictionariesRoute: typeof AdminDictionariesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTendersRoute: typeof AdminTendersRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRouteWithChildren,
  AdminBidsRoute: AdminBidsRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDictionariesRoute: AdminDictionariesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTendersRoute: AdminTendersRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
