/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminWorkflowRouteImport } from './routes/_admin/workflow'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminTendersRouteImport } from './routes/_admin/tenders'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminNotificationsRouteImport } from './routes/_admin/notifications'
import { Route as AdminDictionariesRouteImport } from './routes/_admin/dictionaries'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminCompaniesRouteImport } from './routes/_admin/companies'
import { Route as AdminCalendarRouteImport } from './routes/_admin/calendar'
import { Route as AdminCabinetRouteImport } from './routes/_admin/cabinet'
import { Route as AdminBidsRouteImport } from './routes/_admin/bids'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin/analytics'
import { Route as AdminTendersIndexRouteImport } from './routes/_admin/tenders.index'
import { Route as AdminTendersTenderIdRouteImport } from './routes/_admin/tenders.$tenderId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkflowRoute = AdminWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTendersRoute = AdminTendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDictionariesRoute = AdminDictionariesRouteImport.update({
  id: '/dictionaries',
  path: '/dictionaries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCabinetRoute = AdminCabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBidsRoute = AdminBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTendersIndexRoute = AdminTendersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTendersRoute,
} as any)
const AdminTendersTenderIdRoute = AdminTendersTenderIdRouteImport.update({
  id: '/$tenderId',
  path: '/$tenderId',
  getParentRoute: () => AdminTendersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/bids': typeof AdminBidsRoute
  '/cabinet': typeof AdminCabinetRoute
  '/calendar': typeof AdminCalendarRoute
  '/companies': typeof AdminCompaniesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/dictionaries': typeof AdminDictionariesRoute
  '/notifications': typeof AdminNotificationsRoute
  '/settings': typeof AdminSettingsRoute
  '/tenders': typeof AdminTendersRouteWithChildren
  '/users': typeof AdminUsersRoute
  '/workflow': typeof AdminWorkflowRoute
  '/tenders/$tenderId': typeof AdminTendersTenderIdRoute
  '/tenders/': typeof AdminTendersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/bids': typeof AdminBidsRoute
  '/cabinet': typeof AdminCabinetRoute
  '/calendar': typeof AdminCalendarRoute
  '/companies': typeof AdminCompaniesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/dictionaries': typeof AdminDictionariesRoute
  '/notifications': typeof AdminNotificationsRoute
  '/settings': typeof AdminSettingsRoute
  '/users': typeof AdminUsersRoute
  '/workflow': typeof AdminWorkflowRoute
  '/tenders/$tenderId': typeof AdminTendersTenderIdRoute
  '/tenders': typeof AdminTendersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/analytics': typeof AdminAnalyticsRoute
  '/_admin/bids': typeof AdminBidsRoute
  '/_admin/cabinet': typeof AdminCabinetRoute
  '/_admin/calendar': typeof AdminCalendarRoute
  '/_admin/companies': typeof AdminCompaniesRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/dictionaries': typeof AdminDictionariesRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/tenders': typeof AdminTendersRouteWithChildren
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/workflow': typeof AdminWorkflowRoute
  '/_admin/tenders/$tenderId': typeof AdminTendersTenderIdRoute
  '/_admin/tenders/': typeof AdminTendersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/bids'
    | '/cabinet'
    | '/calendar'
    | '/companies'
    | '/dashboard'
    | '/dictionaries'
    | '/notifications'
    | '/settings'
    | '/tenders'
    | '/users'
    | '/workflow'
    | '/tenders/$tenderId'
    | '/tenders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/bids'
    | '/cabinet'
    | '/calendar'
    | '/companies'
    | '/dashboard'
    | '/dictionaries'
    | '/notifications'
    | '/settings'
    | '/users'
    | '/workflow'
    | '/tenders/$tenderId'
    | '/tenders'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/analytics'
    | '/_admin/bids'
    | '/_admin/cabinet'
    | '/_admin/calendar'
    | '/_admin/companies'
    | '/_admin/dashboard'
    | '/_admin/dictionaries'
    | '/_admin/notifications'
    | '/_admin/settings'
    | '/_admin/tenders'
    | '/_admin/users'
    | '/_admin/workflow'
    | '/_admin/tenders/$tenderId'
    | '/_admin/tenders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/workflow': {
      id: '/_admin/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AdminWorkflowRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tenders': {
      id: '/_admin/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof AdminTendersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notifications': {
      id: '/_admin/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dictionaries': {
      id: '/_admin/dictionaries'
      path: '/dictionaries'
      fullPath: '/dictionaries'
      preLoaderRoute: typeof AdminDictionariesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/companies': {
      id: '/_admin/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/calendar': {
      id: '/_admin/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cabinet': {
      id: '/_admin/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof AdminCabinetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/bids': {
      id: '/_admin/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof AdminBidsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tenders/': {
      id: '/_admin/tenders/'
      path: '/'
      fullPath: '/tenders/'
      preLoaderRoute: typeof AdminTendersIndexRouteImport
      parentRoute: typeof AdminTendersRoute
    }
    '/_admin/tenders/$tenderId': {
      id: '/_admin/tenders/$tenderId'
      path: '/$tenderId'
      fullPath: '/tenders/$tenderId'
      preLoaderRoute: typeof AdminTendersTenderIdRouteImport
      parentRoute: typeof AdminTendersRoute
    }
  }
}

interface AdminTendersRouteChildren {
  AdminTendersTenderIdRoute: typeof AdminTendersTenderIdRoute
  AdminTendersIndexRoute: typeof AdminTendersIndexRoute
}

const AdminTendersRouteChildren: AdminTendersRouteChildren = {
  AdminTendersTenderIdRoute: AdminTendersTenderIdRoute,
  AdminTendersIndexRoute: AdminTendersIndexRoute,
}

const AdminTendersRouteWithChildren = AdminTendersRoute._addFileChildren(
  AdminTendersRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBidsRoute: typeof AdminBidsRoute
  AdminCabinetRoute: typeof AdminCabinetRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDictionariesRoute: typeof AdminDictionariesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTendersRoute: typeof AdminTendersRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkflowRoute: typeof AdminWorkflowRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBidsRoute: AdminBidsRoute,
  AdminCabinetRoute: AdminCabinetRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDictionariesRoute: AdminDictionariesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTendersRoute: AdminTendersRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkflowRoute: AdminWorkflowRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
